[project]
name = "api-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "google-generativeai>=0.8.5",
    "requests>=2.32.0",
    "uvicorn[standard]>=0.35.0",
]
